(() => {
  "use strict";
  const FILE_KEY="financeDropboxSelectedFile";const $=id=>document.getElementById(id),status=(t,c="")=>{const n=$("syncStatus");if(n){n.textContent=t;n.className=`sync-status ${c}`.trim();}},read=k=>{try{return JSON.parse(localStorage.getItem(k)||"null")}catch{return null}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let selected=read(FILE_KEY),buffer=null,workbook=null,rows=null;
  const auth=()=>window.FinanceDropboxAuth,xlsx=()=>window.FinanceXlsx;
  async function client(){const c=await auth().getClient();if(!c)throw new Error("Bitte Dropbox verbinden. Das Zugriffstoken ist nicht vorhanden oder abgelaufen.");return c;}
  function connected(v){$("dropboxLogin")?.classList.toggle("hidden",v);$("dropboxLogout")?.classList.toggle("hidden",!v);if($("dropboxAccount"))$("dropboxAccount").textContent=v?"Dropbox verbunden":"Nicht verbunden";}
  async function list(){const c=await client();status("Dropbox-App-Ordner wird gelesen …");let r=await c.filesListFolder({path:"",recursive:false,include_deleted:false}),all=[...(r.result?.entries||[])];while(r.result?.has_more){r=await c.filesListFolderContinue({cursor:r.result.cursor});all.push(...(r.result?.entries||[]));}const files=all.filter(f=>(f[".tag"]||f.tag)==="file"&&/\.(xlsx|xlsm)$/i.test(f.name||"")),s=$("dropboxFiles");s.replaceChildren();files.forEach(f=>{const o=document.createElement("option");o.value=f.path_lower||f.path_display;o.textContent=f.name;o.dataset.meta=JSON.stringify(f);s.append(o);});s.classList.toggle("hidden",!files.length);$("useDropboxFile")?.classList.toggle("hidden",!files.length);if(!files.length){status("Im Dropbox-App-Ordner liegt noch keine Excel-Datei. Du kannst deine aktuelle Datei direkt hier hochladen.","warn");$("selectedDropboxFile").textContent="Noch keine Excel-Datei in Dropbox.";return;}const pref=selected?.path_lower||selected?.path_display,match=files.find(f=>(f.path_lower||f.path_display)===pref);if(match)s.value=match.path_lower||match.path_display;status(`${files.length} Excel-Datei${files.length===1?"":"en"} im App-Ordner gefunden.`,"good");}
  async function choose(){const o=$("dropboxFiles").options[$("dropboxFiles").selectedIndex];if(!o)throw new Error("Bitte eine Excel-Datei auswählen.");selected=JSON.parse(o.dataset.meta);write(FILE_KEY,selected);$("selectedDropboxFile").textContent=`${selected.name} · Dropbox-App-Ordner`;await download();}
  async function upload(file){if(!file)return;if(!/\.(xlsx|xlsm)$/i.test(file.name))throw new Error("Für die Dropbox-Synchronisierung bitte eine .xlsx- oder .xlsm-Datei verwenden.");const c=await client();status(`${file.name} wird in den Dropbox-App-Ordner hochgeladen …`);const r=await c.filesUpload({path:`/${file.name}`,contents:file,mode:{".tag":"overwrite"},autorename:false,mute:true});selected=r.result;write(FILE_KEY,selected);$("selectedDropboxFile").textContent=`${selected.name} · Dropbox-App-Ordner`;await list();await download();status("Excel-Datei ist in Dropbox abgelegt und bereit zur Datenerfassung.","good");}
  function blob(r){if(r.fileBlob)return r.fileBlob;if(r.fileBinary)return new Blob([r.fileBinary]);if(r.contents instanceof Blob)return r.contents;throw new Error("Die Excel-Datei konnte nicht aus Dropbox gelesen werden.");}
  async function download(){const c=await client();if(!selected)throw new Error("Bitte zuerst eine Dropbox-Datei auswählen.");status(`${selected.name} wird aus Dropbox geladen …`);const res=await c.filesDownload({path:selected.path_display||selected.path_lower}),r=res.result||{},b=blob(r);buffer=await b.arrayBuffer();selected={...selected,...r};delete selected.fileBlob;delete selected.fileBinary;write(FILE_KEY,selected);workbook=XLSX.read(buffer,{type:"array",cellDates:true});if(!workbook.Sheets[xlsx().INPUT])throw new Error(`Das Tabellenblatt „${xlsx().INPUT}“ fehlt.`);rows=XLSX.utils.sheet_to_json(workbook.Sheets[xlsx().INPUT],{header:1,defval:null,raw:true});months();render();if(typeof parseAndShow==="function")await parseAndShow(buffer,{name:`${selected.name} · Dropbox`,importedAt:new Date().toISOString(),source:"Dropbox"},true);status("Dropbox-Datei geladen. Du kannst jetzt Monatsstände ändern.","good");}
  function months(){const s=$("entryMonth"),h=rows?.[0]||[];s.replaceChildren();xlsx().MONTH_COLS.forEach((_,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=h[10+i]||`Monat ${i+1}`;s.append(o);});const m=Number($("monthSelect")?.value);s.value=Number.isInteger(m)&&m>=0&&m<12?String(m):String(new Date().getMonth());}
  function parse(v){let t=String(v??"").trim();if(!t)return null;t=t.replace(/\s/g,"").replace(/€/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".");const n=Number(t);return Number.isFinite(n)?n:null;}function fmt(v){if(v==null||v==="")return"";const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("de-DE",{maximumFractionDigits:2}).format(n):"";}
  function render(){if(!rows)return;const m=Number($("entryMonth").value||0),col=10+m,c=$("entryRows");c.replaceChildren();let filled=0,total=0;for(let r=1;r<=24;r++){const row=rows[r]||[];if(!row[0]||!row[1])continue;total++;if(row[col]!=null&&row[col]!=="")filled++;const w=document.createElement("div");w.className="entry-row";const info=document.createElement("div");info.className="entry-info";const a=document.createElement("strong");a.textContent=row[1];const b=document.createElement("span");b.textContent=`${row[5]||row[4]||"Asset"} · ${row[6]||""} · ${row[8]||""}`;const h=document.createElement("small");h.textContent=row[9]||"Kontostand / Marktwert";info.append(a,b,h);const lab=document.createElement("label");lab.className="entry-input-wrap";const e=document.createElement("span");e.textContent="€";const input=document.createElement("input");input.type="text";input.inputMode="decimal";input.autocomplete="off";input.dataset.row=String(r);input.value=fmt(row[col]);input.setAttribute("aria-label",`${row[1]} in Euro`);lab.append(e,input);w.append(info,lab);c.append(w);}$("entrySummary").textContent=`${filled} von ${total} Monatsständen ausgefüllt.`;$("saveEntries").classList.remove("hidden");}
  async function save(){const c=await client();if(!rows||!buffer||!selected)throw new Error("Bitte zuerst die Dropbox-Excel-Datei laden.");const m=Number($("entryMonth").value||0),col=10+m;$("entryRows").querySelectorAll("input[data-row]").forEach(i=>rows[Number(i.dataset.row)][col]=parse(i.value));status("Kennzahlen werden aktualisiert und Excel-Datei vorbereitet …");const metrics=xlsx().compute(rows,xlsx().params(workbook)),updated=await xlsx().patch(buffer,rows,m,metrics,selected.name);const mode=selected.rev?{".tag":"update",update:selected.rev}:{".tag":"overwrite"};status("Aktualisierte Excel-Datei wird nach Dropbox gespeichert …");let up;try{up=await c.filesUpload({path:selected.path_display||selected.path_lower,contents:updated,mode,autorename:false,mute:true,strict_conflict:true});}catch(e){const msg=String(e?.error?.error_summary||e?.message||"");if(msg.includes("conflict")||msg.includes("rev"))throw new Error("Die Excel-Datei wurde zwischenzeitlich in Dropbox geändert. Bitte zuerst neu laden, damit keine Änderungen überschrieben werden.");throw e;}selected=up.result;write(FILE_KEY,selected);buffer=await updated.arrayBuffer();workbook=XLSX.read(buffer,{type:"array",cellDates:true});if(typeof parseAndShow==="function")await parseAndShow(buffer,{name:`${selected.name} · Dropbox`,importedAt:new Date().toISOString(),source:"Dropbox"},true);if($("monthSelect")){$("monthSelect").value=String(m);$("monthSelect").dispatchEvent(new Event("change"));}render();status("Gespeichert ✓ Excel-Datei und PWA-Dashboard sind aktualisiert.","good");}
  function wire(){$("redirectUriValue").value=auth().redirectUri();$("dropboxAppKey").value=auth().appKey();if(selected)$("selectedDropboxFile").textContent=`${selected.name||"Excel-Datei"} · Dropbox-App-Ordner`;$("entryToggle")?.addEventListener("click",()=>$("syncPanel").classList.toggle("hidden"));$("syncClose")?.addEventListener("click",()=>$("syncPanel").classList.add("hidden"));$("saveDropboxAppKey")?.addEventListener("click",()=>{try{auth().saveAppKey($("dropboxAppKey").value);status("Dropbox App-Key lokal auf diesem Gerät gespeichert.","good");}catch(e){status(e.message,"bad");}});$("dropboxLogin")?.addEventListener("click",()=>auth().startLogin($("dropboxAppKey").value).catch(e=>status(e.message,"bad")));$("dropboxLogout")?.addEventListener("click",()=>{auth().disconnect();connected(false);status("Dropbox getrennt. App-Key und Dateiauswahl bleiben lokal gespeichert.");});$("refreshDropboxFiles")?.addEventListener("click",()=>list().catch(e=>status(e.message,"bad")));$("useDropboxFile")?.addEventListener("click",()=>choose().catch(e=>status(e.message,"bad")));$("uploadDropboxButton")?.addEventListener("click",()=>$("dropboxUploadInput").click());$("dropboxUploadInput")?.addEventListener("change",async e=>{try{await upload(e.target.files?.[0]);}catch(x){status(x.message,"bad");}finally{e.target.value="";}});$("entryMonth")?.addEventListener("change",render);$("loadEntries")?.addEventListener("click",()=>download().catch(e=>status(e.message,"bad")));$("saveEntries")?.addEventListener("click",()=>save().catch(e=>status(e.message,"bad")));}
  async function init(){wire();try{const done=await auth().completeLogin();connected(done||auth().isConnected());if(done){status("Dropbox ist verbunden. Die App sieht nur ihren eigenen App-Ordner.","good");await list();return;}if(auth().isConnected())await list();}catch(e){console.error(e);connected(false);status(e.message||"Dropbox konnte nicht initialisiert werden.","bad");}}
  init();
})();
