(() => {
  "use strict";
  const INPUT="03_Monatsstaende", EVAL="04_Monatsauswertung", PARAM="05_Ziele_Parameter";
  const MONTH_COLS=["K","L","M","N","O","P","Q","R","S","T","U","V"];
  const METRICS=["Aktiva Gesamt","Passiva Gesamt","Nettovermögen","Veränderung ggü. Vormonat","YTD-Veränderung","Liquidität frei","Rücklagen","Wertpapiere / Depot","Bitcoin / Krypto","Edelmetalle","Immobilien","Sonstige Assets","Business-Liquidität","Schweden-Liquidität / Assets","Kreditkarten / Verbindlichkeiten","Liquiditätsreserve (Monate)","Schuldenquote","Bitcoin-Anteil an Aktiva","Immobilien-Anteil an Aktiva","Depot-Anteil an Aktiva","Konzentration größte Assetklasse","Score Liquidität","Score Verschuldung","Score Diversifikation","Score Vermögenswachstum","Finanzscore Gesamt","Fehlende Monatsstände"];
  const num=v=>{if(typeof v==="number"&&Number.isFinite(v))return v;if(v===null||v===undefined||v==="")return 0;const n=Number(String(v).replace(/\./g,"").replace(",","."));return Number.isFinite(n)?n:0;};
  function params(workbook){const rows=XLSX.utils.sheet_to_json(workbook.Sheets[PARAM],{header:1,defval:null,raw:true}),m=new Map();rows.slice(1).forEach(r=>{if(r[0]!=null)m.set(String(r[0]).trim(),r[1]);});return m;}
  function compute(rows,p){const out=new Map(METRICS.map(n=>[n,Array(12).fill(0)])),cost=num(p.get("Monatl. Lebenshaltungskosten")),reserveTarget=num(p.get("Ziel-Notgroschen")),growthTarget=num(p.get("Jahresziel Vermögenswachstum"));const rec=[];for(let r=1;r<=24;r++){const row=rows[r]||[];if(row[0]&&row[1])rec.push(row);}for(let m=0;m<12;m++){const c=10+m,eligible=r=>String(r[8]||"").trim()!=="Nein",sum=fn=>rec.reduce((a,r)=>a+(fn(r)?num(r[c]):0),0);const a=sum(r=>r[6]==="Aktiv"&&eligible(r)),d=sum(r=>r[6]==="Passiv"&&eligible(r)),net=a-d,liq=sum(r=>r[5]==="Liquidität"&&r[6]==="Aktiv"&&r[3]!=="Business"),res=sum(r=>r[5]==="Rücklagen"&&r[6]==="Aktiv"),dep=sum(r=>r[5]==="Wertpapiere"&&r[6]==="Aktiv"),btc=sum(r=>r[5]==="Bitcoin"&&r[6]==="Aktiv"),met=sum(r=>r[5]==="Edelmetalle"&&r[6]==="Aktiv"),imm=sum(r=>r[5]==="Immobilien"&&r[6]==="Aktiv"),oth=sum(r=>r[5]==="Sonstige"&&r[6]==="Aktiv"),bus=sum(r=>r[3]==="Business"&&r[6]==="Aktiv"),swe=sum(r=>r[3]==="Schweden"&&r[6]==="Aktiv"),liab=sum(r=>r[6]==="Passiv"),rm=cost?(liq+res)/cost:0,dr=a?d/a:0,bs=a?btc/a:0,is=a?imm/a:0,ds=a?dep/a:0,conc=a?Math.max(liq+res,dep,btc,met,imm,bus+oth)/a:0,missing=rec.reduce((n,r)=>n+((r[c]===null||r[c]===undefined||r[c]==="")?1:0),0);[["Aktiva Gesamt",a],["Passiva Gesamt",d],["Nettovermögen",net],["Liquidität frei",liq],["Rücklagen",res],["Wertpapiere / Depot",dep],["Bitcoin / Krypto",btc],["Edelmetalle",met],["Immobilien",imm],["Sonstige Assets",oth],["Business-Liquidität",bus],["Schweden-Liquidität / Assets",swe],["Kreditkarten / Verbindlichkeiten",liab],["Liquiditätsreserve (Monate)",rm],["Schuldenquote",dr],["Bitcoin-Anteil an Aktiva",bs],["Immobilien-Anteil an Aktiva",is],["Depot-Anteil an Aktiva",ds],["Konzentration größte Assetklasse",conc],["Fehlende Monatsstände",missing]].forEach(([k,v])=>out.get(k)[m]=v);}const net=out.get("Nettovermögen");for(let m=0;m<12;m++){const mom=m?net[m]-net[m-1]:0,ytd=net[m]-net[0],rm=out.get("Liquiditätsreserve (Monate)")[m],dr=out.get("Schuldenquote")[m],conc=out.get("Konzentration größte Assetklasse")[m],sl=reserveTarget?Math.min(100,rm/reserveTarget*100):0,sd=dr<=.2?100:dr<=.4?80:dr<=.6?55:25,sdiv=conc<=.5?100:conc<=.7?75:45,sg=growthTarget?Math.min(100,Math.max(0,ytd)/growthTarget*100):0;out.get("Veränderung ggü. Vormonat")[m]=mom;out.get("YTD-Veränderung")[m]=ytd;out.get("Score Liquidität")[m]=sl;out.get("Score Verschuldung")[m]=sd;out.get("Score Diversifikation")[m]=sdiv;out.get("Score Vermögenswachstum")[m]=sg;out.get("Finanzscore Gesamt")[m]=Math.round((sl+sd+sdiv+sg)/4);}return out;}
  function norm(base,target){if(target.startsWith("/"))return target.replace(/^\/+/ ,"");const out=[];for(const p of `${base}/${target}`.split("/")){if(!p||p===".")continue;p===".."?out.pop():out.push(p);}return out.join("/");}
  async function sheetPath(zip,name){const p=new DOMParser(),w=p.parseFromString(await zip.file("xl/workbook.xml").async("text"),"application/xml"),r=p.parseFromString(await zip.file("xl/_rels/workbook.xml.rels").async("text"),"application/xml"),s=[...w.getElementsByTagNameNS("*","sheet")].find(x=>x.getAttribute("name")===name);if(!s)throw new Error(`Tabellenblatt „${name}“ nicht im XLSX-Paket gefunden.`);const id=s.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id")||s.getAttribute("r:id"),rel=[...r.getElementsByTagNameNS("*","Relationship")].find(x=>x.getAttribute("Id")===id);if(!rel)throw new Error(`Interner Verweis für „${name}“ fehlt.`);return norm("xl",rel.getAttribute("Target"));}
  function row(doc,n){const data=doc.getElementsByTagNameNS("*","sheetData")[0];let r=[...data.getElementsByTagNameNS("*","row")].find(x=>Number(x.getAttribute("r"))===n);if(r)return r;r=doc.createElementNS(data.namespaceURI,"row");r.setAttribute("r",String(n));const next=[...data.getElementsByTagNameNS("*","row")].find(x=>Number(x.getAttribute("r"))>n);next?data.insertBefore(r,next):data.appendChild(r);return r;}
  function setNum(doc,ref,value,keepFormula=false){const m=/^([A-Z]+)(\d+)$/.exec(ref);if(!m)throw new Error(`Ungültige Excel-Zelle: ${ref}`);const r=row(doc,Number(m[2]));let c=[...r.getElementsByTagNameNS("*","c")].find(x=>x.getAttribute("r")===ref);if(!c){c=doc.createElementNS(r.namespaceURI,"c");c.setAttribute("r",ref);r.appendChild(c);}if(!keepFormula)[...c.getElementsByTagNameNS("*","f")].forEach(x=>x.remove());[...c.getElementsByTagNameNS("*","is")].forEach(x=>x.remove());[...c.getElementsByTagNameNS("*","v")].forEach(x=>x.remove());c.removeAttribute("t");if(value===null||value===undefined||value==="")return;const v=doc.createElementNS(c.namespaceURI,"v");v.textContent=String(Number(value));c.appendChild(v);}
  async function patch(buffer,rows,month,metrics,fileName){if(!window.JSZip)throw new Error("JSZip konnte nicht geladen werden.");const zip=await JSZip.loadAsync(buffer),p=new DOMParser(),s=new XMLSerializer();const ip=await sheetPath(zip,INPUT),id=p.parseFromString(await zip.file(ip).async("text"),"application/xml"),col=MONTH_COLS[month];for(let r=2;r<=25;r++)setNum(id,`${col}${r}`,(rows[r-1]||[])[10+month]);zip.file(ip,s.serializeToString(id));const ep=await sheetPath(zip,EVAL),ed=p.parseFromString(await zip.file(ep).async("text"),"application/xml");METRICS.forEach((name,i)=>{const vals=metrics.get(name)||Array(12).fill(0);for(let m=0;m<12;m++)setNum(ed,`${String.fromCharCode(66+m)}${i+2}`,vals[m],true);});zip.file(ep,s.serializeToString(ed));const pp=await sheetPath(zip,PARAM),pd=p.parseFromString(await zip.file(pp).async("text"),"application/xml");setNum(pd,"B2",month+1);zip.file(pp,s.serializeToString(pd));const wd=p.parseFromString(await zip.file("xl/workbook.xml").async("text"),"application/xml"),root=wd.documentElement;let calc=wd.getElementsByTagNameNS("*","calcPr")[0];if(!calc){calc=wd.createElementNS(root.namespaceURI,"calcPr");root.appendChild(calc);}calc.setAttribute("calcMode","auto");calc.setAttribute("fullCalcOnLoad","1");calc.setAttribute("forceFullCalc","1");zip.file("xl/workbook.xml",s.serializeToString(wd));const mime=/\.xlsm$/i.test(fileName||"")?"application/vnd.ms-excel.sheet.macroEnabled.12":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";return zip.generateAsync({type:"blob",mimeType:mime,compression:"DEFLATE"});}
  window.FinanceXlsx={INPUT,EVAL,PARAM,MONTH_COLS,METRICS,params,compute,patch};
})();
